version: '3.5'

x-logging:
  &default-logging
  driver: json-file
  options:
    max-file: '5'
    max-size: '10m'

services:
  cmc:
    image: poller
    logging: *default-logging
    build:
      context: .
      dockerfile: Dockerfile
      args:
        REQUIREMENTSFILE: requirements.txt
    environment:
      CONFIG: cmc-poller/cmc.yml
  coinbasepro:
    image: pollercbpro
    logging: *default-logging
    build:
      context: .
      dockerfile: Dockerfile
      args:
        REQUIREMENTSFILE: requirements-CBPro.txt
    environment:
      CONFIG: exchange-listener/coinbasepro.yml
  binance:
    image: pollerbinance
    logging: *default-logging
    build:
      context: .
      dockerfile: Dockerfile
      args:
        REQUIREMENTSFILE: requirements-Binance.txt
    environment:
      CONFIG: exchange-listener/binance.yml
  bitstamp:
    image: poller
    logging: *default-logging
    environment:
      CONFIG: exchange-listener/bitstamp.yml
  kraken:
    image: poller
    logging: *default-logging
    environment:
      CONFIG: exchange-listener/kraken.yml
  poloniex:
    image: pollerpoloniex
    logging: *default-logging
    build:
      context: .
      dockerfile: Dockerfile
      args:
        REQUIREMENTSFILE: requirements-Poloniex.txt
    environment:
      CONFIG: exchange-listener/poloniex.yml
  #poloniex:
  #  image: poller
  #  environment:
  #    CONFIG: exchange-poller/poloniex.yml
  oanda:
    image: poller
    logging: *default-logging
    environment:
      CONFIG: exchange-poller/oanda.yml
  sfox:
    image: poller
    logging: *default-logging
    environment:
      CONFIG: exchange-listener/sfox.yml
    restart: always
    
  # bittrex:
  #   image: poller
  #   environment:
  #     CONFIG: exchange-poller/bittrex.yml
networks:
  default:
    external:
      name: crypto