version: '3.5'
services:
  cmc:
    image: poller
    build:
      context: .
      dockerfile: Dockerfile
      args:
        REQUIREMENTSFILE: requirements.txt
    environment:
      CONFIG: cmc-poller/cmc.yml
  coinbasepro:
    image: pollerCBPro
    build:
      context: .
      dockerfile: Dockerfile
      args:
        REQUIREMENTSFILE: requirements-CBPro.txt
    environment:
      CONFIG: exchange-listener/coinbasepro.yml
  bitstamp:
    image: poller
    environment:
      CONFIG: exchange-listener/bitstamp.yml
  kraken:
    image: poller
    environment:
      CONFIG: exchange-listener/kraken.yml
  poloniex:
    image: poller
    environment:
      CONFIG: exchange-poller/poloniex.yml
  binance:
    image: poller
    environment:
      CONFIG: exchange-poller/binance.yml
  oanda:
    image: poller
    environment:
      CONFIG: exchange-poller/oanda.yml
  sfox:
    image: poller
    environment:
      CONFIG: exchange-listener/sfox.yml
    restart: always
  # bittrex:
  #   image: poller
  #   environment:
  #     CONFIG: exchange-poller/bittrex.yml
networks:
  default:
    external:
      name: crypto
