version: '3.5'
services:
  cmc:
    image: poller
    build: .
    environment:
      POLLER_CONFIG: cmc-poller/cmc.yml
  coinbasepro:
    image: poller
    environment:
      POLLER_CONFIG: exchange-poller/coinbasepro.yml
  bitstamp:
    image: poller
    environment:
      POLLER_CONFIG: exchange-poller/bitstamp.yml
  kraken:
    image: poller
    environment:
      POLLER_CONFIG: exchange-poller/kraken.yml
  # bittrex:
  #   image: poller
  #   environment:
  #     POLLER_CONFIG: exchange-poller/bittrex.yml
networks:
  default:
    external:
      name: crypto
