exchange: 
  name: bitstamp
  symbols: 
    - 'BTC/EUR'
    - 'ETH/BTC'
    - 'BTC/USD'
    - 'ETH/USD'
    - 'BCH/EUR'
    - 'BCH/BTC'
    - 'LTC/EUR'
    - 'ETH/EUR' 
    - 'XRP/BTC'
    - 'LTC/BTC'
proxy:
  address: http://172.31.16.10:3000
  ip_pool_size: 4
kafka:
  address: kafka.cryptoindex.me:9092
  topic: orderbook