exchange: 
  name: bittrex
  symbols: 
    - 'XRP/BTC'
    - 'BTC/USD'
    - 'BCH/BTC'
    - 'BTC/USD'
    - 'LTC/BTC'
    - 'XRP/ETH'
    - 'BCH/ETH'
    - 'ETH/BTC'
    - 'LTC/ETH'
    - 'BCH/USDT'
proxy:
  address: http://172.31.16.12:3000
  ip_pool_size: 4
kafka:
  address: kafka.cryptoindex.me:9092
  topic: orderbook