handler: exchange-poller.py
exchange: 
  name: poloniex
  symbols: 
    - 'BCH/BTC'
    - 'XRP/BTC'
    - 'LTC/BTC'
    - 'ETH/BTC'
    - 'ETC/BTC'
    - 'ETC/ETH'
    - 'LTC/USDT'
proxy:
  address: http://172.31.16.10:3000
  ip_pool_size: 4
kafka:
  address: kafka.cryptoindex.me:9092
  topic: orderbook