handler: bitstamp-listener.py
exchange: 
  name: bitstamp
  symbols:
    - 'BTC/USD'
    - 'BTC/EUR'
    - 'BCH/USD'
    - 'ETH/EUR'
    - 'BCH/EUR'
    - 'XRP/EUR'
    - 'LTC/EUR'
    - 'ETH/BTC'
    - 'LTC/BTC'
    - 'BCH/BTC'
    - 'XRP/BTC'
    - 'ETH/USD'
    - 'LTC/USD'
    - 'XRP/USD'
kafka:
  address: kafka.cryptoindex.me:9092
  topic: orderbook