handler: poloniex-listener.py
exchange: 
  name: poloniex
  symbols:
    - 'DASH/BTC'
    - 'LTC/BTC'
    - 'XEM/BTC'
    - 'XMR/BTC'
    - 'XRP/BTC'
    - 'ETH/BTC'
    - 'ETC/BTC'
    - 'ETC/ETH'
    - 'BCH/BTC'
    - 'EOS/BTC'
    - 'EOS/ETH'
    - 'BTC/USDC'
    - 'ETH/USDC'
    - 'BCH/USDC'
    - 'XRP/USDC'
    - 'LTC/USDC'

kafka:
  address: kafka.cryptoindex.me:9092
  topic: orderbook