exchange: 
  name: coinmarketcap
  symbols: 
    - 'USD'
    - 'BTC'
    - 'ETH'
    - 'EUR'
    - 'GBP'
proxy:
  address: http://18.130.227.240:3000
  ip_pool_size: 4
kafka:
  address: kafka:9092
  topic: orderbook