exchange: 
  name: coinmarketcap
  symbols: 
    - 'USD'
    - 'BTC'
    - 'ETH'
    - 'EUR'
    - 'GBP'
proxy:
  address: http://proxy1.cryptoindex.me:3000
  ip_pool_size: 4
kafka:
  address: kafka.cryptoindex.me:9092
  topic: orderbook