version: '3.5'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    networks:
      - crypto
    ports:
      - "2181:2181"
  kafka:
    build: .
    networks:
      - crypto
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_CREATE_TOPICS: "orderbook:1:1"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./kafka-logs:/kafka
networks:
  crypto:
    name: crypto
    driver: bridge